/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s4[7] = {0, 4, 0, 0, 0, 0, 0};

/* OCL_Pendulum_cost_ext_cost_e_fun_jac_hess:(i0[4],i1[],i2[],i3[])->(o0,o1[4],o2[4x4],o3[],o4[0x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=8.7462935601052795e+03;
  a1=arg[0]? arg[0][0] : 0;
  a2=(a0*a1);
  a3=1.3300245633709731e+03;
  a4=arg[0]? arg[0][1] : 0;
  a5=(a3*a4);
  a2=(a2+a5);
  a5=-1.7706551546087430e+03;
  a6=arg[0]? arg[0][2] : 0;
  a7=(a5*a6);
  a2=(a2+a7);
  a7=-1.7591093784532998e+03;
  a8=arg[0]? arg[0][3] : 0;
  a9=(a7*a8);
  a2=(a2+a9);
  a9=(a2*a1);
  a10=(a3*a1);
  a11=2.0498854742910103e+02;
  a12=(a11*a4);
  a10=(a10+a12);
  a12=-2.7370089243983944e+02;
  a13=(a12*a6);
  a10=(a10+a13);
  a13=-2.7214717468045637e+02;
  a14=(a13*a8);
  a10=(a10+a14);
  a14=(a10*a4);
  a9=(a9+a14);
  a14=(a5*a1);
  a15=(a12*a4);
  a14=(a14+a15);
  a15=1.1796218053341713e+03;
  a16=(a15*a6);
  a14=(a14+a16);
  a16=6.8485569278332866e+02;
  a17=(a16*a8);
  a14=(a14+a17);
  a17=(a14*a6);
  a9=(a9+a17);
  a17=(a7*a1);
  a18=(a13*a4);
  a17=(a17+a18);
  a18=(a16*a6);
  a17=(a17+a18);
  a18=6.2400151133034217e+02;
  a19=(a18*a8);
  a17=(a17+a19);
  a19=(a17*a8);
  a9=(a9+a19);
  if (res[0]!=0) res[0][0]=a9;
  a9=(a7*a8);
  a19=(a5*a6);
  a9=(a9+a19);
  a19=(a3*a4);
  a9=(a9+a19);
  a9=(a9+a2);
  a0=(a0*a1);
  a9=(a9+a0);
  if (res[1]!=0) res[1][0]=a9;
  a9=(a13*a8);
  a0=(a12*a6);
  a9=(a9+a0);
  a9=(a9+a10);
  a11=(a11*a4);
  a9=(a9+a11);
  a3=(a3*a1);
  a9=(a9+a3);
  if (res[1]!=0) res[1][1]=a9;
  a9=(a16*a8);
  a9=(a9+a14);
  a15=(a15*a6);
  a9=(a9+a15);
  a12=(a12*a4);
  a9=(a9+a12);
  a5=(a5*a1);
  a9=(a9+a5);
  if (res[1]!=0) res[1][2]=a9;
  a18=(a18*a8);
  a17=(a17+a18);
  a16=(a16*a6);
  a17=(a17+a16);
  a13=(a13*a4);
  a17=(a17+a13);
  a7=(a7*a1);
  a17=(a17+a7);
  if (res[1]!=0) res[1][3]=a17;
  a17=1.7492587120210559e+04;
  if (res[2]!=0) res[2][0]=a17;
  a17=2.6600491267419461e+03;
  if (res[2]!=0) res[2][1]=a17;
  a7=-3.5413103092174861e+03;
  if (res[2]!=0) res[2][2]=a7;
  a1=-3.5182187569065995e+03;
  if (res[2]!=0) res[2][3]=a1;
  if (res[2]!=0) res[2][4]=a17;
  a17=4.0997709485820207e+02;
  if (res[2]!=0) res[2][5]=a17;
  a17=-5.4740178487967887e+02;
  if (res[2]!=0) res[2][6]=a17;
  a13=-5.4429434936091275e+02;
  if (res[2]!=0) res[2][7]=a13;
  if (res[2]!=0) res[2][8]=a7;
  if (res[2]!=0) res[2][9]=a17;
  a17=2.3592436106683426e+03;
  if (res[2]!=0) res[2][10]=a17;
  a17=1.3697113855666573e+03;
  if (res[2]!=0) res[2][11]=a17;
  if (res[2]!=0) res[2][12]=a1;
  if (res[2]!=0) res[2][13]=a13;
  if (res[2]!=0) res[2][14]=a17;
  a17=1.2480030226606843e+03;
  if (res[2]!=0) res[2][15]=a17;
  return 0;
}

CASADI_SYMBOL_EXPORT int OCL_Pendulum_cost_ext_cost_e_fun_jac_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s0;
    case 2: return casadi_s3;
    case 3: return casadi_s1;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int OCL_Pendulum_cost_ext_cost_e_fun_jac_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
